/**
 * Fury Cutter - Premiere Pro Label Applicator
 * 
 * This script reads the automation_blocks JSON file generated by fury_cutter
 * and applies labels to clips in the active sequence based on battle timecodes.
 * 
 * Usage with Automation Blocks:
 * 1. Use the "Execute JSX" block to run this script
 * 2. Or run directly from Premiere Pro: File > Scripts > Run Script
 * 
 * The script will prompt you to select the _automation_blocks.json file.
 */

// Premiere Pro label color indices (0-15)
// These map to the label names in Project Settings > General > Label Colors
var LABEL_INDICES = {
    "Violet": 0,
    "Iris": 1,
    "Caribbean": 2,
    "Lavender": 3,
    "Cerulean": 4,
    "Forest": 5,
    "Rose": 6,
    "Mango": 7,
    "Purple": 8,
    "Blue": 9,
    "Teal": 10,
    "Magenta": 11,
    "Tan": 12,
    "Green": 13,
    "Brown": 14,
    "Yellow": 15
};

// Custom label name mapping - maps your custom label names to Premiere's internal indices
// Update these to match your Premiere Pro label configuration
// Based on your screenshot, your custom labels are:
var CUSTOM_LABEL_MAP = {
    "Enemy Leader": 0,      // Position 0 (Violet slot)
    "Default": 1,           // Position 1 (Iris slot)
    "Caribbean": 2,         // Position 2
    "Lavender": 3,          // Position 3
    "Cerulean": 4,          // Position 4
    "Postgame": 5,          // Position 5 (Forest slot)
    "Error": 6,             // Position 6 (Rose slot)
    "Enemy Boss": 7,        // Position 7 (Mango slot)
    "Purple": 8,            // Position 8
    "Blue": 9,              // Position 9
    "Champion": 10,         // Position 10 (Teal slot)
    "Magenta": 11,          // Position 11
    "Rival": 12,            // Position 12 (Tan slot)
    "Gym": 13,              // Position 13 (Green slot)
    "Brown": 14,            // Position 14
    "E4": 15                // Position 15 (Yellow slot)
};

/**
 * Get label index from label name
 */
function getLabelIndex(labelName) {
    // First check custom labels
    if (CUSTOM_LABEL_MAP.hasOwnProperty(labelName)) {
        return CUSTOM_LABEL_MAP[labelName];
    }
    // Fall back to standard Premiere labels
    if (LABEL_INDICES.hasOwnProperty(labelName)) {
        return LABEL_INDICES[labelName];
    }
    // Default to Cerulean (4) if not found
    return 4;
}

/**
 * Convert seconds to Premiere Pro ticks
 * Premiere uses ticks internally (254016000000 ticks per second)
 */
function secondsToTicks(seconds) {
    var TICKS_PER_SECOND = 254016000000;
    return seconds * TICKS_PER_SECOND;
}

/**
 * Read JSON file and parse it
 */
function readJSONFile(filePath) {
    var file = new File(filePath);
    if (!file.exists) {
        alert("File not found: " + filePath);
        return null;
    }
    
    file.open("r");
    var content = file.read();
    file.close();
    
    try {
        // ExtendScript doesn't have native JSON, so we use eval
        // This is safe since we control the file content
        var data = eval("(" + content + ")");
        return data;
    } catch (e) {
        alert("Error parsing JSON: " + e.message);
        return null;
    }
}

/**
 * Check if a clip overlaps with a time range
 */
function clipOverlapsRange(clip, startTicks, endTicks) {
    var clipStart = clip.start.ticks;
    var clipEnd = clip.end.ticks;
    
    // Check for any overlap
    return (clipStart < endTicks && clipEnd > startTicks);
}

/**
 * Apply labels to clips in the active sequence
 */
function applyLabelsFromJSON(jsonPath) {
    // Check if we have an active sequence
    var seq = app.project.activeSequence;
    if (!seq) {
        alert("No active sequence. Please open a sequence first.");
        return;
    }
    
    // Read the JSON file
    var data = readJSONFile(jsonPath);
    if (!data || !data.labels) {
        alert("Invalid JSON file or no labels found.");
        return;
    }
    
    var labelsApplied = 0;
    var clipsModified = 0;
    
    // Process each label entry
    for (var i = 0; i < data.labels.length; i++) {
        var labelEntry = data.labels[i];
        var labelName = labelEntry.label;
        var startSeconds = labelEntry.start_seconds;
        var endSeconds = labelEntry.end_seconds;
        var trainerName = labelEntry.trainer;
        
        var labelIndex = getLabelIndex(labelName);
        var startTicks = secondsToTicks(startSeconds);
        var endTicks = secondsToTicks(endSeconds);
        
        // Search through all video tracks
        for (var t = 0; t < seq.videoTracks.numTracks; t++) {
            var track = seq.videoTracks[t];
            
            // Search through all clips in this track
            for (var c = 0; c < track.clips.numItems; c++) {
                var clip = track.clips[c];
                
                // Check if clip overlaps with the battle time range
                if (clipOverlapsRange(clip, startTicks, endTicks)) {
                    // Apply the label
                    try {
                        clip.projectItem.setColorLabel(labelIndex);
                        clipsModified++;
                    } catch (e) {
                        // Some clips might not support labels
                    }
                }
            }
        }
        
        labelsApplied++;
    }
    
    alert("Fury Cutter Label Application Complete!\n\n" +
          "Battles processed: " + labelsApplied + "\n" +
          "Clips labeled: " + clipsModified);
}

/**
 * Main entry point
 */
function main() {
    // Prompt user to select the JSON file
    var jsonFile = File.openDialog("Select Fury Cutter Automation Blocks JSON", "JSON Files:*.json");
    
    if (jsonFile) {
        applyLabelsFromJSON(jsonFile.fsName);
    }
}

// Run the script
main();

